
import { Product } from './product/product.component';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'iPhone 15 (128GB)',
    description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
    price: 79999,
    imageUrl: '../../assets/i15.jpg',
    availability:true,
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max (512GB)',
    description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
    price: 179900,
    imageUrl: '../../assets/i15pro.jpg',
    availability:true,
  },
  {
    id: 3,
    name: 'Oversized T-shirt',
    description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
    price: 400,
    imageUrl: '../../assets/white.jpg',
    availability:false,
  },
  {
    id: 4,
    name: 'Anime T-shirt',
    description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
    price: 499,
    imageUrl: '../../assets/cloth_anime.jpg',
    availability:true,
  },
  
  {
    id: 5,
    name: 'Tfortees',
    description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
    price: 999,
    imageUrl: '../../assets/tfortees.jpg',
    availability:true,
  },
  {
    id: 6,
    name: 'Wrist Band',
    description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
    price: 179900,
    imageUrl: '../../assets/wrist.webp',
    availability:false,
  },
  {
    id: 1,
    name: 'iPhone 15 (128GB)',
    description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
    price: 79999,
    imageUrl: '../../assets/i15.jpg',
    availability:true,
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max (512GB)',
    description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
    price: 179900,
    imageUrl: '../../assets/i15pro.jpg',
    availability:true,
  },
  {
    id: 3,
    name: 'Oversized T-shirt',
    description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
    price: 400,
    imageUrl: '../../assets/white.jpg',
    availability:false,
  },
  {
    id: 4,
    name: 'Anime T-shirt',
    description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
    price: 499,
    imageUrl: '../../assets/cloth_anime.jpg',
    availability:true,
  },
  
  {
    id: 5,
    name: 'Tfortees',
    description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
    price: 999,
    imageUrl: '../../assets/tfortees.jpg',
    availability:true,
  },
  {
    id: 6,
    name: 'Wrist Band',
    description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
    price: 179900,
    imageUrl: '../../assets/wrist.webp',
    availability:false,
  },
  {
    id: 1,
    name: 'iPhone 15 (128GB)',
    description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
    price: 79999,
    imageUrl: '../../assets/i15.jpg',
    availability:true,
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max (512GB)',
    description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
    price: 179900,
    imageUrl: '../../assets/i15pro.jpg',
    availability:true,
  },
  {
    id: 3,
    name: 'Oversized T-shirt',
    description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
    price: 400,
    imageUrl: '../../assets/white.jpg',
    availability:false,
  },
  {
    id: 4,
    name: 'Anime T-shirt',
    description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
    price: 499,
    imageUrl: '../../assets/cloth_anime.jpg',
    availability:true,
  },
  
  {
    id: 5,
    name: 'Tfortees',
    description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
    price: 999,
    imageUrl: '../../assets/tfortees.jpg',
    availability:true,
  },
  {
    id: 6,
    name: 'Wrist Band',
    description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
    price: 179900,
    imageUrl: '../../assets/wrist.webp',
    availability:false,
  },
  {
    id: 1,
    name: 'iPhone 15 (128GB)',
    description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
    price: 79999,
    imageUrl: '../../assets/i15.jpg',
    availability:true,
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max (512GB)',
    description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
    price: 179900,
    imageUrl: '../../assets/i15pro.jpg',
    availability:true,
  },
  {
    id: 3,
    name: 'Oversized T-shirt',
    description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
    price: 400,
    imageUrl: '../../assets/white.jpg',
    availability:false,
  },
  {
    id: 4,
    name: 'Anime T-shirt',
    description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
    price: 499,
    imageUrl: '../../assets/cloth_anime.jpg',
    availability:true,
  },
  
  {
    id: 5,
    name: 'Tfortees',
    description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
    price: 999,
    imageUrl: '../../assets/tfortees.jpg',
    availability:true,
  },
  {
    id: 6,
    name: 'Wrist Band',
    description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
    price: 179900,
    imageUrl: '../../assets/wrist.webp',
    availability:false,
  },

  {id: 1,
  name: 'iPhone 15 (128GB)',
  description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
  price: 79999,
  imageUrl: '../../assets/i15.jpg',
  availability:true,
},
{
  id: 2,
  name: 'iPhone 15 Pro Max (512GB)',
  description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
  price: 179900,
  imageUrl: '../../assets/i15pro.jpg',
  availability:true,
},
{
  id: 3,
  name: 'Oversized T-shirt',
  description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
  price: 400,
  imageUrl: '../../assets/white.jpg',
  availability:false,
},
{
  id: 4,
  name: 'Anime T-shirt',
  description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
  price: 499,
  imageUrl: '../../assets/cloth_anime.jpg',
  availability:true,
},

{
  id: 5,
  name: 'Tfortees',
  description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
  price: 999,
  imageUrl: '../../assets/tfortees.jpg',
  availability:true,
},
{
  id: 6,
  name: 'Wrist Band',
  description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
  price: 179900,
  imageUrl: '../../assets/wrist.webp',
  availability:false,
},
{
  id: 1,
  name: 'iPhone 15 (128GB)',
  description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
  price: 79999,
  imageUrl: '../../assets/i15.jpg',
  availability:true,
},
{
  id: 2,
  name: 'iPhone 15 Pro Max (512GB)',
  description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
  price: 179900,
  imageUrl: '../../assets/i15pro.jpg',
  availability:true,
},
{
  id: 3,
  name: 'Oversized T-shirt',
  description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
  price: 400,
  imageUrl: '../../assets/white.jpg',
  availability:false,
},
{
  id: 4,
  name: 'Anime T-shirt',
  description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
  price: 499,
  imageUrl: '../../assets/cloth_anime.jpg',
  availability:true,
},

{
  id: 5,
  name: 'Tfortees',
  description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
  price: 999,
  imageUrl: '../../assets/tfortees.jpg',
  availability:true,
},
{
  id: 6,
  name: 'Wrist Band',
  description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
  price: 179900,
  imageUrl: '../../assets/wrist.webp',
  availability:false,
},
{
  id: 1,
  name: 'iPhone 15 (128GB)',
  description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
  price: 79999,
  imageUrl: '../../assets/i15.jpg',
  availability:true,
},
{
  id: 2,
  name: 'iPhone 15 Pro Max (512GB)',
  description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
  price: 179900,
  imageUrl: '../../assets/i15pro.jpg',
  availability:true,
},
{
  id: 3,
  name: 'Oversized T-shirt',
  description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
  price: 400,
  imageUrl: '../../assets/white.jpg',
  availability:false,
},
{
  id: 4,
  name: 'Anime T-shirt',
  description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
  price: 499,
  imageUrl: '../../assets/cloth_anime.jpg',
  availability:true,
},

{
  id: 5,
  name: 'Tfortees',
  description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
  price: 999,
  imageUrl: '../../assets/tfortees.jpg',
  availability:true,
},
{
  id: 6,
  name: 'Wrist Band',
  description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
  price: 179900,
  imageUrl: '../../assets/wrist.webp',
  availability:false,
},
{
  id: 1,
  name: 'iPhone 15 (128GB)',
  description: 'A16 Bionic chip, 6‑core CPU with 2 performance and 4 efficiency cores, 5‑core GPU,16‑core Neural Engine',
  price: 79999,
  imageUrl: '../../assets/i15.jpg',
  availability:true,
},
{
  id: 2,
  name: 'iPhone 15 Pro Max (512GB)',
  description: 'A17 Pro chip, New 6-core CPU with 2 performance and 4 efficiency cores, New 6‑core GPU, New 16‑core Neural Engine',
  price: 179900,
  imageUrl: '../../assets/i15pro.jpg',
  availability:true,
},
{
  id: 3,
  name: 'Oversized T-shirt',
  description: 'BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men',
  price: 400,
  imageUrl: '../../assets/white.jpg',
  availability:false,
},
{
  id: 4,
  name: 'Anime T-shirt',
  description: 'THALASI Anime Printed Oversized T-Shirts for Men - Down Shoulder Loose Fit Black T-Shirt for Men & Goku, One Piece and Naruto Printed T Shirt for Men',
  price: 499,
  imageUrl: '../../assets/cloth_anime.jpg',
  availability:true,
},

{
  id: 5,
  name: 'Tfortees',
  description: 'Tfortees Black Cotton Printed Tshirt Oversized for Men',
  price: 999,
  imageUrl: '../../assets/tfortees.jpg',
  availability:true,
},
{
  id: 6,
  name: 'Wrist Band',
  description: 'ABoldfit Cotton Wrist Band for Men & Women, Wrist Supporter for Gym Wrist Wrap/Straps Gym Accessories for Men for Hand Grip & Wrist Support While Workout & Muscle Relaxation',
  price: 179900,
  imageUrl: '../../assets/wrist.webp',
  availability:false,
},
  
  
];
